### ISSUE TITLE
Горячие клавиши

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2021-7-2d-game#19]
Добавьте в README.md описания горячих клавиш. Методом тыка я нашёл, что **A** — вправо, **D** — влево, **W** — прыжок. А что ещё можно делать — непонятно.

P.S. Оценки буду выставлять завтра.

**Comment by Mazdaywik** [comment]
Я в игры этого жанра не играл и не очень понимаю, что нужно делать. Горячие клавиши действительно работают. Буквы и цифры добавляют иконки в квадратики снизу. Нажатая кнопка мыши оставляет туманный свет на экране, который тут же исчезает.

Только дальше что с этим делать — не понял. Щелчок мышью по своему персонажу или противнику ничего не даёт.

Одно окно браузера:
![image](https://user-images.githubusercontent.com/1309859/134493351-0ca44b17-3149-4399-9b95-89954ee7a17a.png)

Другое окно браузера:
![image](https://user-images.githubusercontent.com/1309859/134493463-def4f830-7a05-4edf-b6ee-d5ff7cc04b78.png)

Окно консоли:
![image](https://user-images.githubusercontent.com/1309859/134493491-f661283f-d68b-4d92-a942-8e7b1e91665e.png)

**Comment by Ankalot** [comment]
@Mazdaywik  Сами заклинания (которые должны появляться после удачного начертания (это надо зажатым лкм какие-либо знаки чертить на экране)) не реализованы, но планировались (в отчете это написано). То есть по сути атаковать нечем (заклинаний и состояний (баффов и дебаффов) в игре нет, хотя это планировалось).

**Comment by p0rtale** [comment]
@Mazdaywik в консоли пишется результат распознавания следующих шаблонов:
![Screenshot_20210923_181410](https://user-images.githubusercontent.com/30365990/134535013-052f7819-ba40-467b-91ec-582018a0014b.png)

spellId: 0
![Screenshot_20210923_182049](https://user-images.githubusercontent.com/30365990/134536072-15540851-5eb7-4dcd-b566-07641c331f92.png)

spellId: 1
![Screenshot_20210923_182354](https://user-images.githubusercontent.com/30365990/134536377-fdb1bcfc-e706-4f57-a371-517369c482fd.png)

spellId: 2
![Screenshot_20210923_183135](https://user-images.githubusercontent.com/30365990/134537670-dd5ead0a-83a4-45a5-8f24-a34c1e49e468.png)

spellId: 3
![Screenshot_20210923_183328](https://user-images.githubusercontent.com/30365990/134537990-97deb1a3-d705-479f-a40f-d2faeded50cd.png)

spellId: 4
![Screenshot_20210923_183659](https://user-images.githubusercontent.com/30365990/134538645-4aaac69b-3ab9-4c78-8821-efbcc4bbe943.png)

spellId: 5
![Screenshot_20210923_183812](https://user-images.githubusercontent.com/30365990/134538851-342f471a-94f4-43ef-8e1c-e103bdbeb8d7.png)

spellId: 6
![Screenshot_20210923_183851](https://user-images.githubusercontent.com/30365990/134538957-4083dd3d-9a06-4896-bc9d-d9127f21ed9b.png)

spellId: 7
![Screenshot_20210923_184302](https://user-images.githubusercontent.com/30365990/134539718-2b11457d-733e-4dae-8c19-ed5e586c0648.png)

spellId: 8
![Screenshot_20210923_184432](https://user-images.githubusercontent.com/30365990/134539986-2c192c66-5f52-4c83-9971-b6c90ce4ed02.png)
